config/routes.rb
CryptographyBasics::Application.routes.draw do

  root "welcome#index"

  get "binary_number" => "binary_number#index"

  get "binary_number_exercises/1" => "binary_number_exercises#exercise1"
  post "binary_number_exercises/1" => "binary_number_exercises#check1"
  get "binary_number_exercises/2" => "binary_number_exercises#exercise2"
  post "binary_number_exercises/2" => "binary_number_exercises#check2"

  get "caesar_cipher" => "caesar_cipher#index"

  get "caesar_cipher_exercises/1" => "caesar_cipher_exercises#exercise1"
  post "caesar_cipher_exercises/1" => "caesar_cipher_exercises#check1"
  get "caesar_cipher_exercises/2" => "caesar_cipher_exercises#exercise2"
  post "caesar_cipher_exercises/2" => "caesar_cipher_exercises#check2"

  get "caesar_cipher_brute_force" => "caesar_cipher_brute_force#index"

  get "ascii_code" => "ascii_code#index"

  get "ascii_code_exercises/1" => "ascii_code_exercises#exercise1"
  post "ascii_code_exercises/1" => "ascii_code_exercises#check1"
  get "ascii_code_exercises/2" => "ascii_code_exercises#exercise2"
  post "ascii_code_exercises/2" => "ascii_code_exercises#check2"

  get "simple_substitution_cipher" => "simple_substitution_cipher#index"

  get "simple_substitution_cipher_exercises/1" => "simple_substitution_cipher_exercises#exercise1"
  post "simple_substitution_cipher_exercises/1" => "simple_substitution_cipher_exercises#check1"
  get "simple_substitution_cipher_exercises/2" => "simple_substitution_cipher_exercises#exercise2"
  post "simple_substitution_cipher_exercises/2" => "simple_substitution_cipher_exercises#check2"

  get "simple_substitution_cipher_brute_force" => "simple_substitution_cipher_brute_force#index"

  get "exclusive_or" => "exclusive_or#index"

  get "one_time_pad" => "one_time_pad#index"

  get "one_time_pad_exercises/1" => "one_time_pad_exercises#exercise1"
  post "one_time_pad_exercises/1" => "one_time_pad_exercises#check1"
  get "one_time_pad_exercises/2" => "one_time_pad_exercises#exercise2"
  post "one_time_pad_exercises/2" => "one_time_pad_exercises#check2"

  

end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ascii_code_controller.rb
class AsciiCodeController < ApplicationController
  include AsciiCodeFunctions
  
  before_filter :extract_params
  
  def index
  end
end

app/controllers/ascii_code_exercises_controller.rb
class AsciiCodeExercisesController < ApplicationController
  include AsciiCodeFunctions
  include SharedFunctions
  
  before_filter :extract_params
  
  def exercise1
    generate_answer1
  end

  def check1
    check(session["ascii_code"]["binary_array"].join == params["answer"])
  end

  def exercise2
    generate_answer1
  end

  def check2
    check(session["ascii_code"]["word"] == params["answer"])
  end
end

app/controllers/binary_number_controller.rb
class BinaryNumberController < ApplicationController
  include BinaryNumberFunctions
  
  before_filter :extract_params
  
  def index
  end
end

app/controllers/caesar_cipher_controller.rb
class CaesarCipherController < ApplicationController
  include CaesarCipherFunctions
  before_filter :extract_params
  
  def index
    @before = "akiyama"
    @after = encrypt(@before, @key)
  end
end

app/controllers/exclusive_or_controller.rb
class ExclusiveOrController < ApplicationController
  include BinaryNumberFunctions
  before_filter :extract_params
  
  def index
  end
end

app/controllers/one_time_pad_controller.rb
class OneTimePadController < ApplicationController
  include OneTimePadFunctions
  before_filter :extract_params
  
  def index
    @before = "get"
    @plain = word_to_binary_array(@before)
    @after = encrypt(@plain)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def split_binary_str(binary_str)
    binary_str.scan(/.{8}|.+$/)
  end
end

app/helpers/ascii_code_exercises_helper.rb
module AsciiCodeExercisesHelper
end

app/helpers/ascii_code_helper.rb
module AsciiCodeHelper
end

app/helpers/binary_number_exercises_helper.rb
module BinaryNumberExercisesHelper
end

app/helpers/binary_number_helper.rb
module BinaryNumberHelper
end

app/helpers/caesar_cipher_brute_force_helper.rb
module CaesarCipherBruteForceHelper
end

app/helpers/caesar_cipher_exercises_helper.rb
module CaesarCipherExercisesHelper
end

app/helpers/caesar_cipher_helper.rb
module CaesarCipherHelper
end

app/helpers/exclusive_or_helper.rb
module ExclusiveOrHelper
end

app/helpers/one_time_pad_exercises_helper.rb
module OneTimePadExercisesHelper
end

app/helpers/one_time_pad_helper.rb
module OneTimePadHelper
end

app/helpers/simple_substitution_cipher_helper.rb
module SimpleSubstitutionCipherHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ascii_code/_ascii_code.html.erb
<h2>ASCIIコード表</h2>

<p>コンピュータ上で2進数を用いて文字列を表現する際に広く利用されている割り当て方法です．ASCII Code にはアルファベットしか含まれていませんが，現在は Unicode という漢字やハングルなど世界中の文字を含む文字コードが使われています．ASCII Code は Unicode の一部として現在も用いられています．</p>
<p>文字の下に書かれた数字がASCII Codeで，表の左端にはASCII Codeを2進数で表した時の上位4ビット (0/1が4つ分)，表の上端にはASCII Codeの下位4ビット (0/1が4つ分) が表記されています．16進数も合わせて表記されていますので，参考にしてください．

<%= content_tag "table", id: "ascii_code", data: {hint1: @hint1, hint2: @hint2} do %>
  <tr>
    <td class="hint1">
    </td>
    <td class="hint1">
    </td>
    <% (0..15).each do |col| %>
    <td class="hint1">
      <%= sprintf("%04b", col) %>
    </td>
    <% end %>
  </tr>
  <tr>
    <td class="hint1">
    </td>
    <td>
      16進数表記<br/>
      ↓上の桁，→下の桁
    </td>
    <% (0..15).each do |col| %>
    <td class="header">
      <%= sprintf("%X", col) %>
    </td>
    <% end %>
  </tr>
  <% (0..5).each do |row| %>
  <tr>
    <td class="hint1">
      <%= sprintf("%08b", (32 + row * 16))[0..3] %>
    </td>
    <td class="header">
      0x<%= sprintf("%X", (32 + row * 16)) %>
    </td>
    <% (0..15).each do |col| %>
    <td class="character">
      <%= (32 + row * 16 + col).chr %><br/>
      <div class="hint2">(<%= (32 + row * 16 + col) %>)</div>
    </td>
    <% end %>
  </tr>
  <% end %>
<% end %>

app/views/ascii_code/index.html.erb
<% content_for :title do -%>
  文字コード (ASCII Code)
<% end -%>
<h1>文字コード (ASCII Code)（コンピュータ上での文字表現）</h1>

<h2>概要</h2>

コンピュータは文字も2進数で表現しています．世界中で使われてきた2進数での文字の表現方法である ASCII Code について学んでみましょう．

<h2>体験</h2>

<%= form_tag(ascii_code_url(params), :method => :get) do %>
  ヒント1あり <%= radio_button_tag(:hint1, "visible", @hint1.nil? || @hint1 == "visible") %>/
  なし <%= radio_button_tag(:hint1, "hidden", @hint1 == "hidden") %><br/>
  ヒント2あり <%= radio_button_tag(:hint2, "visible", @hint2.nil? || @hint2 == "visible") %>/
  なし <%= radio_button_tag(:hint2, "hidden", @hint2 == "hidden") %><br/>
  <%= submit_tag "設定" %>
<% end %>

<%= render 'ascii_code' %>

<p>
上部の設定項目で，2進数や文字の下のASCII Codeの表示ON/OFFを切り替えられます．
</p>


<h2>問題に挑戦</h2>

<p>上記のASCIIコード表を用いて文字列から2進数への変換，2進数から文字列への変換を体験してみてください．</p>

<%= link_to '演習問題1: 文字列 => 2進数', ascii_code_exercises_1_url(params) %><br/>
<%= link_to '演習問題2: 2進数 => 文字列', ascii_code_exercises_2_url(params) %><br/>

<p>なんだか暗号みたいですね．一見わかりにくくなっているように見えても，その変換の方法をみんなが知っている場合，誰でも読むことができてしまいます．つまり暗号の役割は果たせません．</p>

app/views/ascii_code_exercises/check1.html.erb
<% content_for :title do -%>
  文字コード 演習問題
<% end -%>
<h1>文字コード 演習問題</h2>

<h2>問題 (文字列 => 2進数)</h2>

<div class="result"><%= @result %>です．</div>

<p class="answer">問題: 　　　　<%= session["ascii_code"]["word"] %></p>
<p class="answer">正解: 　　　　<%= session["ascii_code"]["binary_array"].join(", ") %></p>
<p class="answer">あなたの解答: <%= split_binary_str(params["answer"]).join(", ") %></p>

<%= link_to '違う問題にチャレンジ', ascii_code_exercises_1_path %>

app/views/ascii_code_exercises/check2.html.erb
<% content_for :title do -%>
  文字コード 演習問題
<% end -%>
<h1>文字コード 演習問題</h2>

<h2>問題 (2進数 => 文字列)</h2>

<div class="result"><%= @result %>です．</div>

<p class="answer">問題: 　　　　<%= session["ascii_code"]["binary_array"].join(", ") %></p>
<p class="answer">正解: 　　　　<%= session["ascii_code"]["word"] %></p>
<p class="answer">あなたの解答: <%= params["answer"] %></p>

<%= link_to '違う問題にチャレンジ', ascii_code_exercises_2_path %>

app/views/ascii_code_exercises/exercise1.html.erb
<% content_for :title do -%>
  文字コード 演習問題
<% end -%>
<h1>文字コード 演習問題</h1>

<h2>問題 (文字列 => 2進数)</h2>

文字列 <div class="characters"><%= @word %></div> は2進数で表すと（　　）になる．

<p class="notice">※注意：問題文や解答確認画面では便宜上2進数8ビットごとにカンマを表示していますが，解答時にはカンマは入力不要です．</p>

<%= form_tag(ascii_code_exercises_1_path, :method => :post) do %>
  <%= text_field_tag(:answer, @answer, {:size => @word.length * 8 + 6, :maxlength => @word.length * 8}) %>
  <%= submit_tag "解答する" %>
<% end %>

app/views/ascii_code_exercises/exercise2.html.erb
<% content_for :title do -%>
  文字コード 演習問題
<% end -%>
<h1>文字コード 演習問題</h1>

<h2>問題 (2進数 => 文字列)</h2>

<p>2進数 <div class="binary"><%= @binary_array.join(", ") %></div> は文字列で表すと（　　）になる．</p>

<p class="notice">※注意：問題文や解答確認画面では便宜上2進数8ビットごとにカンマを表示しています．</p>

<%= form_tag(ascii_code_exercises_2_path, :method => :post) do %>
  <%= text_field_tag(:answer, @answer, :size => @word.length) %>
  <%= submit_tag "解答する" %>
<% end %>

app/views/binary_number/_binary_cards.html.erb
<%= content_tag "table", id: "cards", data: {nbits: @nbits, type: @type, hint1: @hint1, hint2: @hint2} do %>
<%
  2.times do |t|
%>
  <tr>
<%
    (0..@nbits).each do |i|
      num = 2**(@nbits-1-i)
    %>
    <% if i < @nbits %>
      <% if t == 0 %>
  <th class="hint1">
    <%= num %>
  </th>
      <% else %>
  <td>
    <% if @type == "card" %>
      <%= image_tag(asset_path("card-0.png"), :id => "card-#{num}", :class => "card", :data => {:face_image => asset_path("card-#{num}.png"), :back_image => asset_path("card-0.png")}) %>
    <% else %>
      <%= image_tag(asset_path("binary-0.png"), :id => "card-#{num}", :class => "card", :data => {:face_image => asset_path("binary-1.png"), :back_image => asset_path("binary-0.png")}) %>
    <% end %>
  </td>
      <% end %>
    <% else %>
      <% if t == 0 %>
  <th class="hint1">
　　
  </th>
      <% else %>
  <td id="card-sum" class="hint2">
    0
  </td>
      <% end %>
    <% end %>
  <% end %>
  </tr>
<% end %>
<% end %>

app/views/binary_number/index.html.erb
<% content_for :title do -%>
  2進数
<% end -%>
<h1>2進数（コンピュータの表現方法: <%= @nbits %> bit）</h1>

<h2>概要</h2>

<p>コンピュータは情報をどのように表現しているか知っていますか？実は，0と1の2つの数字で全ての情報を表現しています．この0と1のみで数値を表現する2進法に触れてみましょう．</p>

<h2>体験</h2>

<p>ここではカードを使って2進法を体験してもらいます．カードをクリックするとカードが裏返ります．カードに書かれた数字（丸の数で数字を表しています）を足した数が，2進法が表す数字になります．最初は右端に合計値が出ているので参考にしてください．カードの表の数字もヒントとしてカードの上に表示されています．これらの数字は下の設定で表示しないように変更できます．また，カード自体を本来の数値，0または1に変更することもできます．慣れてきたらヒントを減らして0/1のカードで数字を表現できるか試してみてください．</p>

<%= form_tag(binary_number_url(params), :method => :get) do %>
  ヒント1あり <%= radio_button_tag(:hint1, "visible", @hint1.nil? || @hint1 == "visible") %>/
  なし <%= radio_button_tag(:hint1, "hidden", @hint1 == "hidden") %><br/>
  ヒント2あり <%= radio_button_tag(:hint2, "visible", @hint2.nil? || @hint2 == "visible") %>/
  なし <%= radio_button_tag(:hint2, "hidden", @hint2 == "hidden") %><br/>
  ビット数を他の値に変更できます (0から8)．<%= text_field_tag(:nbits, @nbits, :size => 2) %><br/>
  カードの種類を変更できます．数字 <%= radio_button_tag(:type, "card", @type.nil? || @type == "card") %>/
  0/1 <%= radio_button_tag(:type, "binary", @type == "binary") %><br/>
  <%= submit_tag "設定" %>
<% end %>

<%= render 'binary_cards' %>

<h2>問題に挑戦</h2>

<p>2進法について理解度を確認するための演習問題を用意しています．2進数から10進数への変換およびその逆変換の問題を用意しているので，try してみてください．</p>

<%= link_to '演習問題1: 2進数 => 10進数', binary_number_exercises_1_url(params) %><br/>
<%= link_to '演習問題2: 10進数 => 2進数', binary_number_exercises_2_url(params) %><br/>

app/views/caesar_cipher/_caesar_table.html.erb
<table id="caesar_table">
  <tr>
    <td>暗号化前</td>
    <% (0..25).each do |i| %>
    <td>
      <%= (97 + i).chr %>
    </td>
    <% end %>
  </tr>
  <tr>
    <td></td>
    <% (0..25).each do |i| %>
    <td>↓</td>
    <% end %>
  </tr>
  <tr>
    <td>暗号化後</td>
    <% (0..25).each do |i| %>
    <td>
      <%= (65 + (i + @key) % 26).chr %>
    </td>
    <% end %>
  </tr>
</table>

app/views/caesar_cipher/index.html.erb
<% content_for :title do -%>
  シーザー暗号
<% end -%>
<h1>シーザー暗号</h1>

<h2>概要</h2>

<p>シーザー暗号 (Caesar Cipher) は，ジュリアス・シーザー（ユリウス・カエサル）が使っていたといわれる暗号です．シーザーは紀元前100年ごろにローマで生まれ，活躍した武将です．</p>
<p>シーザー暗号では，平文で使われているアルファベットを，一定の文字数だけ「ずらす」ことによって暗号化を行います．シーザー暗号は日本語にも適用できますが，ここでは簡単のためアルファベットだけを用います．</p>

<h2>体験</h2>

<p>シーザー暗号を体験してみましょう．以下では便宜上，小文字 (a, b, c, ...) で平文のアルファベットを表記し，大文字 (A, B, C, ...) で暗号文のアルファベットを表記します．</p>
<p>シーザー暗号では「ずらす」文字数が暗号鍵に相当しています．現在の暗号鍵は<%= @key %>です．<p>
<%= form_tag(caesar_cipher_path, :method => :get) do %>
  暗号鍵を他の値に変更できます．<%= text_field_tag(:key, @key, :size => 2) %><br/>
  <%= submit_tag "設定" %>
<% end %>

<br/>

<h3>暗号化に用いる表</h3>
<p>上記の暗号鍵でアルファベットを変換した場合，どのような文字に変換されるかを示した表です．</p>
<%= render 'caesar_table' %>

<h3>暗号化の例</h3>

<p>上記の表を用いた場合の暗号化の例を示します．</p>

暗号化前：<%= @before %><br/>
暗号化後：<%= @after %>


<h2>問題に挑戦</h2>

<p>シーザー暗号の演習問題です．上記の表などを活用しながら，理解できたかどうか確認してみてください．</p>

<%= link_to '演習問題1: 暗号化（平文を暗号文にする）', caesar_cipher_exercises_1_path(params) %><br/>
<%= link_to '演習問題2: 復号化（暗号文を平文に戻す）', caesar_cipher_exercises_2_path(params) %><br/>

app/views/one_time_pad/index.html.erb
<% content_for :title do -%>
  使い捨てパッド
<% end -%>
<h1>使い捨てパッド</h1>

<h2>概要</h2>

<p>2進数とASCII Code，そして排他的論理和について学んだあなたは，最強の暗号を学ぶ準備ができました．使い捨てパッドです．使い捨てパッドは2進数の平文に対して，同じ長さの2進数の鍵を用意し，2つの値の排他的論理和を取ることで，暗号文を作成します．鍵は一度しか使わず，毎回異なる値（真の乱数）を使います．鍵を使い終わったら捨ててしまうため「使い捨てパッド」と呼ばれています．</p>

<h2>体験</h2>

<p>コンピュータで計算した乱数 (真の乱数ではありません) ですが，以下にランダムに生成された鍵と，それを用いて暗号化した結果について例を示します．</p>

<h3>暗号化の例</h3>

<p>使い捨てパッドで下記の鍵を用いて文字列を暗号化した例です．使い捨てパッドを適用するためには，文字列を2進数に変換してから適用する必要があります．暗号化後の2進数は文字列で表示することもできますが，文字コードが割り当てられていない値も多くあるため，文字化けしたような読めない文字列になることが多いです．ここでは暗号化後の値は便宜上そのまま2進数で表記します．</p>

暗号化前 (平文)：　　　 <%= @before %><br/>
暗号化前 (平文, 2進数)：<%= @plain.join(", ") %><br/>
鍵：　　　　　　　　　 <%= @key.join(", ") %><br/>
暗号化後 (暗号文)： 　　<%= @after.join(", ") %>


<h2>問題に挑戦</h2>

<p>使い捨てパッドの演習問題です．文字列の2進数への変換，2進数から文字列への変換には，<%= link_to 'ASCIIコード表', ascii_code_path, :target => "_blank" -%>を利用してください．</p>

<%= link_to '演習問題1: 暗号化（平文を暗号文にする）', one_time_pad_exercises_1_url(params.merge(:key => @key)) %><br/>
<%= link_to '演習問題2: 復号化（暗号文を平文に戻す）', one_time_pad_exercises_2_url(params.merge(:key => @key)) %><br/>

<h2>終わりに</h2>

<p>最後まで本アプリケーションを体験いただきありがとうございます．暗号アルゴリズムにおいては，「鍵」がとても大事な役割を果たしていることが理解いただけましたでしょうか？</p>
<p>また，最強の暗号といわれる使い捨てパッドは，比較的シンプルなものであることが理解いただけましたでしょうか？こんなにシンプルで強力な暗号なのに使われているのを聞いたことがないという方もいらっしゃるでしょう．実は使い捨てパッドは暗号化する文書と同じ長さの鍵を暗号文を送りたい相手に事前に「安全」に届ける必要があるのですが，これは文書を安全に届けるのと同じコストがかかってしまいます．しかも鍵が再利用できません．というわけで本当にコストをかけても安全にかつ短い時間で遠隔の人に情報を届けたいときにだけ使える暗号といえます．実際に軍事目的などで利用された実績があります．ただし，私達が普段利用するにはちょっとコストがかかりすぎますね．</p>
<p>実際にはもっと低コストで高い安全性を実現する暗号アルゴリズムがたくさん提案されています．興味をもった人は是非勉強してみてください．</p>

app/views/welcome/index.html.erb
<% content_for :title do -%>
  暗号技術に触れてみよう！
<% end -%>
<h1>暗号技術に触れてみよう！</h1>

<h2>概要</h2>

<p>暗号技術とは何か？Webアプリケーションを用いてコンピュータにおける情報の表現方法，暗号アルゴリズム (共通鍵暗号のみ) の動作などを体験してもらうことで，その概念に触れていただきます．本アプリケーションは文献[<a href="#ref_1">1</a>][<a href="#ref_2">2</a>]を参考に作成されています．</p>
<p>本アプリケーションは以下のような流れで暗号技術が体験できます．</p>

<ol>
  <li><a href="#binary_number">コンピュータでの情報の表現方法</a></li>
  <li><a href="#historical_cipher">歴史的な暗号アルゴリズム</a></li>
  <li><a href="#decipher_of_historical_cipher">歴史的暗号の解読</a></li>
  <li><a href="#one_time_pad">使い捨てパッド</a></li>
</ol>

「2進法」をすでに知っているという人は「歴史的な暗号アルゴリズム」からはじめていただいてもよいですし，いきなり最強の暗号「使い捨てパッド」に進んでいただいても良いかもしれません．また，時間が無い方は「コンピュータでの情報の表現方法」で「2進法」のみ学んでいただいても良いですし，「歴史的な暗号アルゴリズム」のみ触れていただいても良いかと思います．

<a name="binary_number"><h2>コンピュータでの情報の表現方法</h2></a>

<p>コンピュータ上では2進数という形式で情報が扱われています．皆さんが普段目にするアルファベットも，コンピュータ上では2進数で表されています．普段触れている文字を2進数で表現すると，なんだかよくわからない暗号文のように見えます．でも扱い方がわかると皆さんでも2進数を文字として読むことができます．情報の変換（符号化）の際に全ての変換方法が公開されていると，それは暗号にはなりません．ここではまず2進数の扱いについて学んでいただきます．</p>

<ol>
  <li><%= link_to '2進数（コンピュータ上での情報表現)', binary_number_path, :target => "_blank" %></li>
  <li><%= link_to '文字コード（ASCII Code) (コンピュータ上での文字表現）', ascii_code_path, :target => "_blank" %></li>
</ol>

<a name="historical_cipher"><h2>歴史的な暗号アルゴリズム</h2></a>

<p>全ての手順が公開された符号化は暗号ではないことを学びました．では，どうすれば暗号になるのでしょうか？文字の符号化 (アルファベットを2進数に対応づける) を図示すると以下のようになります．</p>

<div class="image">
  <%= image_tag asset_path('encode.png') %><br/>
  図1: 文字の符号化
</div>

<p>符号化の手順は全ての人が知っているので，復号化 (逆変換) ができるとすると，すべての人が復号化できることになります．</p>

<div class="image">
  <%= image_tag asset_path('decode.png') %><br/>
  図2: 文字の復号化
</div>

<p>暗号化 (元の文字 (平文) を読めない文 (暗号文) に変換する) の手順も同様にすべての人に公開されていますが，暗号化に用いる鍵は暗号化・復号化する人だけが知っています．</p>

<div class="image">
  <%= image_tag asset_path('encrypt.png') %><br/>
  図3: 文字の暗号化
</div>

<p>復号化 (逆変換) は，鍵を知っている人だけが行えます．</p>

<div class="image">
  <%= image_tag asset_path('decrypt.png') %><br/>
  図4: 文字の復号化
</div>

<p>このように，暗号化する人と，暗号文を読む人だけが「鍵」という秘密を共有することで，暗号化が実現できます．アリスが暗号化し，ボブが暗号文を受信する例を以下の図に示します．この場合，盗聴者のイブは「鍵」を持っていないので，暗号文を復号することができません．</p>

<div class="image">
  <%= image_tag asset_path('encrypted-communication.png') %><br/>
  図5: 暗号化・復号化を用いた通信
</div>

<p>今では使われなくなりましたが，歴史的な暗号に触れることで，鍵と暗号アルゴリズムの関係について学んでみましょう．</p>

<ol>
  <li><%= link_to 'シーザー暗号', caesar_cipher_path, :target => "_blank" %></li>
  <li><%= link_to '単一換字暗号', simple_substitution_cipher_path, :target => "_blank" %></li>
</ol>

<p>いかがでしょうか？古典暗号について理解していただけたでしょうか？現在使われている暗号も，「ずらす」「置き換える」といった操作を基本としてアルゴリズムが構成されています．鍵と置換操作の関係については，古典暗号と同様な仕組みが今でも用いられているというわけです．ただし，ここで紹介した暗号ではアルファベット文字の単位で置き換え操作を行なっていますが，コンピュータ上では2進数の0/1を置き換えることになります．</p>

<a name="decipher_of_historical_cipher"><h2>歴史的暗号の解読</h2></a>

<p>歴史的暗号が使われなくなったのは，コンピュータを使うことで暗号解読の処理がより短時間で実現できるようになったからです．ここでは，最も単純で確実に暗号を解読出来る方法，「総当たり攻撃」について触れてみましょう．</p>


<ol>
  <li><%= link_to 'シーザー暗号への総当たり攻撃', caesar_cipher_brute_force_path, :target => "_blank" %></li>
  <li><%= link_to '単一換字暗号への総当たり攻撃', simple_substitution_cipher_brute_force_path, :target => "_blank" %></li>
</ol>

<a name="one_time_pad"><h2>使い捨てパッド</h2></a>

<p>「鍵」と「暗号アルゴリズム」について学んだので，後は最強の暗号を学ぶだけです．その前に最強の暗号を使いこなすために必要な「排他的論理和」について触れてみましょう．「排他的論理和」が理解できれば準備完了です．最強の暗号「使い捨てパッド」に触れてみてください．</p>

<ol>
  <li><%= link_to '排他的論理和', exclusive_or_path(:nbits => 1), :target => "_blank" %></li>
  <li><%= link_to '使い捨てパッド', one_time_pad_path, :target => "_blank" %></li>
</ol>


<h3>参考文献</h3>
<ol>
  <a name="ref_1"><li>結城 浩 (著), "新版暗号技術入門 秘密の国のアリス", ソフトバンククリエイティブ (2008)</li></a>
  <a name="ref_2"><li>Tim Bell/Ian H.Witten/Mike Fellows (著), Matt Powell (イラスト), 兼宗 進 (翻訳), "コンピュータを使わない情報教育アンプラグドコンピュータサイエンス", イーテキスト研究所 (2007)</li></a>
</ol>